languageCode: en
title: Weird Ancient Music Instruments
theme: PaperMod
params:
  ShowToc: true
  TocOpen: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

languages:
  en:
    languageName: English
    weight: 1
    taxonomies:
      tag: tags
      category: categories
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 20

markup:
  goldmark:
    renderer:
      unsafe: true
